### PR TITLE
Use 7.3.1-jdk17 docker image to support non-amd64 arch

### PR DESCRIPTION
**Pull request by arall**
https://hub.docker.com/_/gradle?tab=tags&page=1&name=7.3.1-jdk17

### CODE REVIEW

**Comment by bt-nia** [comment]
Can confirm this fix works on M1, it will throw a confusing error message otherwise:
`failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:4dc2b5e2b959d3edb34c424ed0261798bd93b64d70c73e13ceda91605165b696: not found`

**Review by muriloalvesdev — APPROVED** [review]

**Comment by bt-nia** [comment]
@arall you can merge I think

**Comment by arall** [comment]
>Only those with write access to this repository can merge pull requests.

I'm not a maintainer.

**Comment by christophetd** [comment]
Thanks for the contribution! I will merge and push a new Docker image shortly.

**Pull request merged**
